### ISSUE TITLE
Not Actually An Issue...

### ISSUE THREAD

**Issue by WrongProgram1** [4-04/Discord-Reaction-GeneratorBOT#2]
What is your Discord user and discriminator? I'm having difficulties understanding the instructions. ('Cause it's not that specific)

Or do you have like Video tutorials on how you setup everything?

**Comment by 4-04** [comment]
I updated and made the readme.md more clear. Let me know if you're still having problems with this.

**Comment by WrongProgram1** [comment]
![Screenshot_20200531_221131](https://user-images.githubusercontent.com/49438078/83354512-cd65bd80-a38b-11ea-925a-40aa2f4588dc.jpg)

Start won't work😕

**Comment by hyperstore2020** [comment]
@WrongProgram1 His DC Name is Penoqo#0001
